# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: PyPI Publish Package

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Build source distribution only
        run: |
          rm -rf dist
          python -m build --sdist

      - name: Validate metadata
        run: |
          twine check dist/*.tar.gz
      
      - name: Install and test from sdist
        run: |
          python -m venv testenv
          source testenv/bin/activate
          pip install dist/*.tar.gz
          pip install pytest
          pytest

      - name: Upload source to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          twine upload dist/*.tar.gz
